# Production hardening profile
# Activar con: SPRING_PROFILES_ACTIVE=prod

spring.jpa.show-sql=false
logging.level.com.flores.taskcodeback=WARN
logging.level.org.springframework.security=WARN

app.security.swagger-enabled=false

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
